sudo: false
language: php
services: mongodb
before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --no-interaction
  - wget https://scrutinizer-ci.com/ocular.phar
php:
  - 5.4
  - 5.5
  - 5.6
script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - composer check