# this file contains the main configuration for the library
deploy-scripts:
  cf:
    command: cf
    credentials:
      username: lapistano
      password: 'w/mZ2Nh8"'
      org: FIN-GRAVITON
      space: DEV
      api_url: 'https://api.appcloud-nova.swisscom.com'
      domain: ~
    services:
      mongodb: free
      atmoss3: free
